config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :bookmarks
  resource :welcome, only: [:show]

  authenticated :user do
    root 'bookmarks#index', as: :authenticated_root
  end

  root 'welcome#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  after_create :screenshot
  validates :url, format: URI::regexp(%w(http https)), presence: true

  belongs_to :user

  def self.search(query)
    where('url LIKE ?', "%#{query}%")
  end

  private

  def url_title
      URI.parse(url).host.sub(/\Awww\./, '')
  end

  def screenshot
    ws = Webshot::Screenshot.instance
    screenshot = ws.capture url, "#{url_title}.png", width: 300, height: 300, quality: 85
    uploader = Cloudinary::Uploader.upload(screenshot.path)
    update(screenshot_url: uploader['url'])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :bookmarks

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = current_user.bookmarks.page(params[:page]).per_page(6)

    if params[:search]
      @bookmarks = current_user.bookmarks.search(params[:search]).page(params[:page]).per_page(6)
    else
      @bookmarks = current_user.bookmarks.page(params[:page]).per_page(6)
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @link = LinkThumbnailer.generate(@bookmark.url)
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = current_user.bookmarks.create(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: bookmarks_url }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: bookmarks_url }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bookmark
      @bookmark = current_user.bookmarks.find(params[:id])
    end

    def bookmark_params
      params.require(:bookmark).permit(:url, :id_user, :screenshot_url)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.slim
.panel.panel-default
  .panel-body
    .text-center
      = form_for Bookmark.new do |f|
        .field
          .input-group
            span.input-group-addon
              = label_tag "URL"
            = f.text_field :url, placeholder: "Type your link", class: "form-control", autocomplete: :off
        br
        .actions
          = f.submit "Add new bookmark", class: 'btn btn-primary'

app/views/bookmarks/_search_form.html.slim
.panel.panel-default
  .panel-body
    .text-center
      = form_tag(bookmarks_path, method: "get", id: "search-form") do
        .field
          .input-group
            span.input-group-addon
              = label_tag "URL"
            = text_field_tag :search, params[:search], placeholder: "Search by url", class: "form-control", autocomplete: :off
          br
          .actions
            = submit_tag "Search", class: 'btn btn-primary'

app/views/bookmarks/edit.html.slim
h1 Editing Bookmark
= render 'form', bookmark: @bookmark
= link_to 'Show', @bookmark
| |
= link_to 'Back', bookmarks_path

app/views/bookmarks/index.html.slim
.row
  .col-md-6
    = render 'form', bookmark: @bookmark
  .col-md-6
    = render 'bookmarks/search_form'
.row
  .col-md-12
    - unless @bookmarks.present?
      .alert.alert-danger role="alert"
        p
          | By your request bookmarks not found. Try another link
  - @bookmarks.each do |bookmark|
    .col-sm-4.col-lg-4.col-md-4
      .panel.panel-default
        .panel-heading
          h3.panel-title = truncate(bookmark.url, length: 40, omission: '...')
          span.label.label-danger.pull-right
            = link_to bookmark_path(bookmark), method: :delete, remote: true do
              span.glyphicon.glyphicon-remove.remove-x
        .panel-body
            = image_tag bookmark.screenshot_url, class: "img-responsive"

.text-center = will_paginate @bookmarks, renderer: BootstrapPagination::Rails

app/views/bookmarks/new.html.slim
h1 New Bookmark
= render 'form', bookmark: @bookmark
= link_to 'Back', bookmarks_path

app/views/bookmarks/show.html.slim
p#notice= notice
p
  strong Url:
  = @bookmark.url

= link_to 'Edit', edit_bookmark_path(@bookmark)
| \
= link_to 'Back', bookmarks_path

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'BookMarksApp', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li
            = image_tag current_user.image, class: "img-circle"
          li
            a = current_user[:name]
          li
            = link_to 'Logout', destroy_user_session_path, method: :delete
        - unless current_user
          li
            = link_to 'Sign in with Facebook', user_facebook_omniauth_authorize_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TestTaskBm
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      = render 'shared/flashes'
      = yield

app/views/shared/_flashes.html.slim
- flash.each do |name, msg|
  = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dissmissable", role: 'alert' do
    button.close data-dismiss='alert' type='button'
      span aria-hidden='true'
        | &times;
    = msg

app/views/welcome/show.html.slim
.jumbotron
  .text-center
    h1 BOOKMARKS APP
    p
      = link_to 'Sign in with Facebook', user_facebook_omniauth_authorize_path, class: "btn btn-primary btn-lg"